CREATE TABLE USERS (
    ID BIGSERIAL PRIMARY KEY,
    EMAIL TEXT UNIQUE,
    USERNAME TEXT UNIQUE,
    PICTURE_URL TEXT,
    PASSWORD TEXT,
    RATINGS JSONB,
    JOIN_TIME TIMESTAMP WITHOUT TIME ZONE,
    LAST_ONLINE TIMESTAMP WITHOUT TIME ZONE,
    CURRENT_GAME JSONB
);

CREATE INDEX USERS_LAST_ONLINE_IDX ON USERS (LAST_ONLINE);

CREATE TABLE USER_GAME_HISTORY (
    ID BIGSERIAL PRIMARY KEY,
    USER_ID BIGINT,
    GAME_TIME TIMESTAMP WITHOUT TIME ZONE,
    GAME_INFO JSONB
);

CREATE INDEX USER_GAME_HISTORY_USER_ID_GAME_TIME_IDX ON USER_GAME_HISTORY (USER_ID, GAME_TIME);

CREATE TABLE GAME_HISTORY (
    ID BIGSERIAL PRIMARY KEY,
    REPLAY JSONB
);

CREATE TABLE ACTIVE_GAMES (
    ID BIGSERIAL PRIMARY KEY,
    SERVER INT,
    GAME_ID TEXT,
    GAME_INFO JSONB
);

CREATE INDEX ACTIVE_GAMES_SERVER_GAME_ID_IDX ON ACTIVE_GAMES (SERVER, GAME_ID);

CREATE TABLE CAMPAIGN_PROGRESS (
    ID BIGSERIAL PRIMARY KEY,
    USER_ID BIGINT UNIQUE,
    PROGRESS JSONB
);